name:                quizell
version:             0.1.0.0
github:              "levibutcher/quizell"
license:             BSD3
author:              "Levi Butcher"
maintainer:          "example@example.com"
copyright:           "2022 Levi Butcher"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/quizell#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- random-shuffle
- random
- time
- split
- parsec
- lens
- optparse-applicative
- ListZipper
- directory
- filepath
- async
- ansi-terminal
- mtl

library:
  source-dirs: src

executables:
  quizell:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quizell
    - brick
    - vty
    - unix

  quizell2:
    main:                Mainx.hs
    source-dirs:         windows
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Mainx
    dependencies:
    - quizell

tests:
  quizell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quizell
    - QuickCheck >=2.1 && <3
    - HUnit
